### ISSUE TITLE
ORCA-911 Incompatible usage of core_course\local\entity\content_item::__construct()

### ISSUE THREAD

**Issue by NinaHerrmann** [orca-nrw/crossplatform-moodle-lti-plugin#3]
Thanks for the plugin! However, when installed under 4.0 we are getting the error 
```
Exception - Too few arguments to function core_course\local\entity\content_item::__construct(), 8 passed in [dirroot]/mod/orcalti/lib.php on line 286 and exactly 9 expected
```
 -> in 4.0 every mod has a purpose which has to be passed to the constructor. Otherwise, the plugin can not be used.

**Comment by NinaHerrmann** [comment]
To be more precise https://github.com/orca-nrw/crossplatform-moodle-lti-plugin/blob/32c6eca0da3d16ec8fe242593a121701080014e4/lib.php#L313 needs a version distinction to create with or without a purpose.

**Comment by NinaHerrmann** [comment]
To be more precise `lib.php` line 373 and 287 need a case distinction for different versions of moodle calling a constructor with or without purpose :) 
Thanks for considering please notify me if you need any help!

**Comment by Freakrider** [comment]
Thanks Nina. 
@paulneag 
You can see the difference from 3.xx vs 4.xx here: 
https://github.com/moodle/moodle/blob/MOODLE_311_STABLE/mod/lti/lib.php
https://github.com/moodle/moodle/blob/MOODLE_400_STABLE/mod/lti/lib.php

**Comment by KaiOrca** [comment]
Tickeet is closed, since it is QA staging done
