### ISSUE TITLE
ORCA-909 Improvement: Testing connection page

### ISSUE THREAD

**Issue by NinaHerrmann** [orca-nrw/crossplatform-moodle-lti-plugin#5]
The instruction proposes to test the connection by adding an activity - However, as it is a user page, the error messages are not meaningful 
![image](https://user-images.githubusercontent.com/18289780/192322304-88de906b-cd1a-4fc9-a473-3f3fdf10a959.png)

However, the network tab does not give me a 404, so I have to search the code looking for the request (most likely not even been sent) and possible causes without having further information.

**Comment by KaiOrca** [comment]
Ticket is put on QA stag in jira, therefore issue willbe closed
