### ISSUE TITLE
ORCA-907 Improvement: Bad coding style in javascript call

### ISSUE THREAD

**Issue by NinaHerrmann** [orca-nrw/crossplatform-moodle-lti-plugin#6]
when calling mod_form I get the warning
´Too much data passed as arguments to js_call_amd("mod_orcalti/orca_lti_selector-lazy", "init"). Generally there are better ways to pass lots of data from PHP to JavaScript, for example via Ajax, data attributes, ... . This warning is triggered if the argument string becomes longer than 1024 characters.`

Although this is is "merely" a warning you might want to change it, as it is obviously bad coding style.

**Comment by KaiOrca** [comment]
Ticket is closed => QA stag done
