### ISSUE TITLE
ORCA-906 Moodle code style

### ISSUE THREAD

**Issue by NinaHerrmann** [orca-nrw/crossplatform-moodle-lti-plugin#7]
Please check the plugin with the moodle codechecker (https://github.com/moodlehq/moodle-local_codechecker).
Although some parts are discussable, it is best practice to respect guidelines. I would have expected that common moodle development techniques would be known.

**Comment by landesportal-orca** [comment]
ein Ticket ist angelegt: https://projekt-orca-nrw.atlassian.net/browse/ORCA-906

**Comment by landesportal-orca** [comment]
Fixed in develop branch
