### ISSUE TITLE
ORCA - 909 Improvement design redirect page

### ISSUE THREAD

**Issue by NinaHerrmann** [orca-nrw/crossplatform-moodle-lti-plugin#9]
the redirect looks as follows:

![image](https://user-images.githubusercontent.com/18289780/192759822-a5208e15-9378-487e-b7b6-5f624e591c5e.png)

Is there any chance to improve the page?

**Comment by KaiOrca** [comment]
Current status QA staging done. => Ticket closes

**Comment by KaiOrca** [comment]
Ticket was closed now it reopened
